{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_alluredemo.py:11: AssertionError"}, "description": "this test fails", "start": 1616499119406, "stop": 1616499119407, "uuid": "3fefdbf0-40a7-4946-a56b-cd44e80a773f", "historyId": "e3535563f27e644c4a3371e45c952575", "testCaseId": "cdaed0cfb7279459338013af0d443b47", "fullName": "test_alluredemo#test_failure", "labels": [{"name": "suite", "value": "test_alluredemo"}, {"name": "host", "value": "PC-201705071250"}, {"name": "thread", "value": "9252-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_alluredemo"}]}