{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_alluredemo.py:11: AssertionError"}, "description": "this test fails", "start": 1616499168164, "stop": 1616499168165, "uuid": "00c967a8-f699-4855-94db-80d8c18179b5", "historyId": "e3535563f27e644c4a3371e45c952575", "testCaseId": "cdaed0cfb7279459338013af0d443b47", "fullName": "test_alluredemo#test_failure", "labels": [{"name": "suite", "value": "test_alluredemo"}, {"name": "host", "value": "PC-201705071250"}, {"name": "thread", "value": "1532-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_alluredemo"}]}